api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        url_generation_strategy: 0
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
