when@dev:
    doctrine_diagram:
        size: midi
        filename: database
        format: svg

when@test:
    doctrine_diagram:
        size: midi
        filename: test-database
        format: svg
