# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
services:
    Aws\S3\S3Client:
        arguments:
            - version: '2006-03-01'
              region: 'nyc3'
              endpoint: '%env(S3_ENDPOINT)%'
              credentials:
                  key: '%env(AWS_S3_ACCESS_ID)%'
                  secret: '%env(AWS_S3_ACCESS_SECRET)%'


flysystem:
    storages:
        default.storage:
            adapter: 'aws'
            # visibility: public # Make the uploaded file publicly accessible in S3
            options:
                client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                streamReads: true
                prefix: '%env(S3_STORAGE_PREFIX)%'
        # also on production, for thumbnail creation
        local.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/images'


when@dev:
    flysystem:
        storages:
            # comment this out to test s3 on local
            default.storage:
                adapter: 'local'
                # not on production!
                options:
                    directory: '%kernel.project_dir%/public/default-storage'

