# Default configuration for extension with alias: "survos_fw"
survos_fw:
  theme: fw7
  enabled: true
  projects:

    # Prototype
    omar:
      code: omar
      logo: logo/omar.png
      name: OmarExpo

    batsi: # previously pgsc
      code: batsi
      logo: logo/batsi.png
      name: Batsi
      tabs:
        - locations
        - artists
        - obras
      #          - share
      #          - scan
      database: Batsi
      stores:
        - name: artists
          schema: ++id,name
          url: https://pgsc.survos.com/api/artists
        - name: locations
          schema: ++id,name
          url: https://pgsc.survos.com/api/artists
        - name: objects
          schema: ++id,title
          url: https://pgsc.survos.com/api/obras

    modo: # configuration code for database, etc.
      code: modo
      logo: logo/modo.png
      name: El Modo
      tabs:
        - info
          # - share
        # if data is set, composer req survos/js-twig-bundle
        #      data: # must be json-ld

        # indexDb database name
      database: MyDatabase
      stores:

        # Prototype
        - name: items
          url: https://modo.survos.com/api/items
          limit: 100

      members:
        # Prototype
        - email: tacman@gmail.com
          role: PROJECT_ADMIN
