twig:
    file_name_pattern: '*.twig'
    globals:
        app_name: 'El MODO'
        app_logo: '/logo.webp'
        voxitour_base: '%env(VOXITOUR_BASE)%'

when@test:
    twig:
        strict_variables: true
