<?php

namespace App\Controller\Admin;

use Adeliom\EasyAdminUserBundle\Controller\Admin\EasyAdminUserTrait;
use App\Entity\Expo;
use App\Entity\Obj;
use App\Repository\ExpoRepository;
use EasyCorp\Bundle\EasyAdminBundle\Attribute\AdminDashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\Assets;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\MenuItem;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;
use EasyCorp\Bundle\EasyAdminBundle\Router\AdminUrlGenerator;
use Symfony\Bridge\Twig\Attribute\Template;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

//#[AdminDashboard(routePath: '/admin', routeName: 'admin')]
#[AdminDashboard('/{_locale}/')]
class DashboardController extends AbstractDashboardController
{
//    use EasyAdminUserTrait;

    public function __construct(
        private AdminUrlGenerator                             $adminUrlGenerator,
        private ExpoRepository $expoRepository,
        #[Autowire('%kernel.enabled_locales%')] private array $enabledLocales,
    )
    {
    }

    #[Route('/admin', name: 'admin')]
    public function index(): Response
    {
        return $this->render('/admin/dashboard/index.html.twig', [
            'expos' => $this->expoRepository->findBy([], ['code' => 'ASC']),

        ]);
        return parent::index();
        return $this->redirect($this->adminUrlGenerator->setController(ExpoCrudController::class)->generateUrl());
    }

    #[Route('/app', name: 'app_admin')]
    #[Template('/admin/dashboard/index.html.twig')]
    public function app_index(): Response|array
    {
        return [];
        return parent::index();

        // Option 1. You can make your dashboard redirect to some common page of your backend
        //
        // 1.1) If you have enabled the "pretty URLs" feature:
        // return $this->redirectToRoute('admin_user_index');
        //
        // 1.2) Same example but using the "ugly URLs" that were used in previous EasyAdmin versions:
        // $adminUrlGenerator = $this->container->get(AdminUrlGenerator::class);
        // return $this->redirect($adminUrlGenerator->setController(OneOfYourCrudController::class)->generateUrl());

        // Option 2. You can make your dashboard redirect to different pages depending on the user
        //
        // if ('jane' === $this->getUser()->getUsername()) {
        //     return $this->redirectToRoute('...');
        // }

        // Option 3. You can render some custom template to display a proper dashboard with widgets, etc.
        // (tip: it's easier if your template extends from @EasyAdmin/page/content.html.twig)
        //
        // return $this->render('some/path/my-dashboard.html.twig');
    }

    public function configureDashboard(): Dashboard
    {
        return Dashboard::new()
            ->setLocales($this->enabledLocales)
            ->setTitle('Modo');
    }

    public function configureCrud(): Crud
    {
        $crud =  parent::configureCrud(); // TODO: Change the autogenerated stub
        $crud->showEntityActionsInlined(true);
//        $crud->addFormTheme('@EasyMedia/form/easy-media.html.twig');
        return $crud;
    }

    public function configureAssets(): Assets
    {
        return Assets::new()
            ->useCustomIconSet()
            ;
    }


    public function configureMenuItems(): iterable
    {
        yield MenuItem::linkToDashboard('Dashboard', 'home');
        yield MenuItem::linkToCrud('Expo', Expo::class, Expo::class);
        yield MenuItem::linkToCrud('Obj', Obj::class, Obj::class);
//        yield MenuItem::linkToRoute('Medias', 'fa fa-picture-o', 'media.index');
//        yield from $this->administratorMenuEntry();
    }
}
