<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250406113040 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE expo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(32) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE expo_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, translatable_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_349B803F2C2AC5D3 ON expo_translation (translatable_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX expo_translation_unique_translation ON expo_translation (translatable_id, locale)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE expo_translation ADD CONSTRAINT FK_349B803F2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES expo (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE expo_translation DROP CONSTRAINT FK_349B803F2C2AC5D3
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE expo
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE expo_translation
        SQL);
    }
}
